### ISSUE TITLE
调用api刷课bug

### ISSUE THREAD

**Issue by 491676** [1665169869/lmsTech#1]
[在刷客过程中，调用脚本刷客进行到模块专

https://user-images.githubusercontent.com/126304786/235283725-9da1b674-5179-46dc-b2c5-80138fcbd07b.mp4

![QQ截图20230429123418](https://user-images.githubusercontent.com/126304786/235283731-94eeaebf-5db1-42ca-83c7-b28f0e88edd8.png)
题总是卡死，不在进行下一个任务点。还望修复一下

**Comment by 1665169869** [comment]
按F12 - Console控制台看看报错截图

**Comment by 491676** [comment]
> 按F12 - Console控制台看看报错截图

![Uploading QQ截图20230429180107.png…]()

**Comment by 491676** [comment]
> 
![Uploading QQ截图20230429180107.png…]()

**Comment by 491676** [comment]
&nbsp;


校务处
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月29日(星期六) 下午5:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [1665169869/lmsTech] 调用api刷课bug (Issue #1)





 
按F12 - Console控制台看看报错截图

**Comment by 1665169869** [comment]
> 新刊参

你发的图片没法查看

**Comment by 1665169869** [comment]
由于太久没有回复，关闭该issue

**Comment by 1665169869** [comment]
由于太久没有回复，关闭该issue
