### ISSUE TITLE
试一下这个题库？

### ISSUE THREAD

**Issue by maxshq** [1665169869/lmsTech#2]
https://greasyfork.org/scripts/455478-%E5%9B%BD%E5%AE%B6%E5%BC%80%E6%94%BE%E5%A4%A7%E5%AD%A6%E5%AD%A6%E4%B9%A0%E7%BD%91%E9%A2%98%E5%BA%93/code/%E5%9B%BD%E5%AE%B6%E5%BC%80%E6%94%BE%E5%A4%A7%E5%AD%A6%E5%AD%A6%E4%B9%A0%E7%BD%91%E9%A2%98%E5%BA%93.js

**Comment by 1665169869** [comment]
没看懂咋用

**Comment by 1665169869** [comment]
预计不会添加答题功能，如果需要答题建议fork本仓库自己进行添加答题功能的脚本代码
